// Generated by assemble.js — do not edit manually
import NavMinimal from "@/components/NavMinimal";
import HeroSplit from "@/components/HeroSplit";
import StatsRow from "@/components/StatsRow";
import AboutFounder from "@/components/AboutFounder";
import ServicesAlternating from "@/components/ServicesAlternating";
import ProcessSteps from "@/components/ProcessSteps";
import AboutSplit from "@/components/AboutSplit";
import ContactSimple from "@/components/ContactSimple";
import FooterWordmark from "@/components/FooterWordmark";

export default function Home() {
  return (
    <>
      <NavMinimal
        brandName={"Mercer Street Capital"}
        links={[{"label":"Who We Are","href":"#about"},{"label":"Criteria","href":"#services"},{"label":"What We Offer","href":"#offer"},{"label":"Contact","href":"#contact"}]}
        ctaLabel={"Get in Touch"}
        ctaHref={"#contact"}
      />
      <main>
      <HeroSplit
        eyebrow={"Self-Funded Search Fund · Seattle, WA"}
        headline={"Acquire and operate"}
        headlineAccent={"exceptional businesses"}
        body={"Mercer Street Capital is a self-funded search fund seeking to acquire and operate a single, well-managed business between $2M and $20M in revenue. We are committed to preserving what you've built and setting it up for its next chapter."}
        ctaPrimary={"Our Criteria"}
        ctaPrimaryHref={"#services"}
        ctaSecondary={"Get in Touch"}
        ctaSecondaryHref={"#contact"}
        accentWord={"Acquire"}
      />
      <StatsRow
        eyebrow={"By the Numbers"}
        headline={"Focused on one"}
        headlineAccent={"great business"}
        stats={[{"value":"$2M–$20M","label":"Target Revenue Range","note":"Annual recurring revenue"},{"value":"$300K–$2M","label":"Target EBITDA","note":"Consistent, healthy margins"},{"value":"15%+","label":"Minimum EBITDA Margin","note":"Stability requirement"},{"value":"11 yrs","label":"Amazon Operating Experience","note":"Eric Bauer, Founder"}]}
      />
      <AboutFounder
        eyebrow={"Who We Are"}
        headline={"Eric Bauer"}
        headlineAccent={"Founder & Principal"}
        bioP1={"Eric Bauer leads Mercer Street Capital with over 11 years of experience at Amazon.com spanning P&L management of multi-billion dollar categories, business development serving millions of customers, and bringing first-ever technologies to scale — combined with 2+ years of direct SMB operating experience."}
        bioP2={"In 2024, Mercer Street Capital completed its first acquisition — Turner Hat Company — which has since achieved consistent revenue growth, dramatically improved operating margins, reduced customer churn, and promoted employees from within. Eric brings an empathetic, results-driven management style to every company he operates."}
        credentials={[{"label":"Amazon.com Experience","value":"11 Years"},{"label":"SMB Operations","value":"2+ Years"},{"label":"First Acquisition","value":"Turner Hat Company, 2024"},{"label":"Location","value":"Seattle, Washington"}]}
        quote={"I'm not looking for a quick flip. I want to build on what you've already created."}
      />
      <ServicesAlternating
        eyebrow={"What We're Looking For"}
        headline={"Our acquisition"}
        headlineAccent={"criteria"}
        items={[{"title":"Right-Sized Businesses","body":"We target companies with $2M to $20M in annual revenue and $300K to $2M in EBITDA. This range is where a focused, hands-on operator can add the most value.","tag":"Size"},{"title":"Stable, Growing Operations","body":"Consistent growth trajectories and EBITDA margins above 15% are non-negotiable. We want a foundation to build on, not a turnaround situation.","tag":"Stability"},{"title":"Diversified Customer Base","body":"No single anchor customer should dominate revenue. Diversified accounts reflect genuine product-market fit and reduce transition risk.","tag":"Customers"},{"title":"Owner Ready to Transition","body":"We work with owners who are committed to selling and have no clear internal succession plan. We offer a thoughtful, personal path for your business's next chapter.","tag":"Succession"},{"title":"Wholesale, Distribution & Consumer Goods","body":"Our primary focus is on companies in wholesale, distribution, and consumer goods — but we're open to compelling opportunities across any industry.","tag":"Industry"}]}
      />
      <ProcessSteps
        eyebrow={"Our Process"}
        headline={"Simple, transparent,"}
        headlineAccent={"founder-focused"}
        body={"From first conversation to closing, we move with purpose and respect your time. No games, no re-trades."}
        steps={[{"title":"Initial Conversation","body":"A confidential, no-pressure call to learn about your business and share how we work. No NDA required upfront."},{"title":"Letter of Intent","body":"If there's mutual interest, we move quickly to a clear, simple LOI that sets honest expectations for both sides."},{"title":"Due Diligence","body":"A focused, efficient process. We're operators, not auditors — we look for what matters and don't use diligence as a reason to re-trade."},{"title":"Close & Transition","body":"We work with you and your advisors to structure an acquisition that protects your employees, your customers, and your legacy."}]}
      />
      <AboutSplit
        eyebrow={"What We Offer"}
        headline={"Preserve your"}
        headlineAccent={"legacy"}
        body={"Mercer Street Capital is not a private equity firm or a strategic acquirer. We are solely focused on acquiring a single business and continuing its operations with care and long-term commitment."}
        statement={"We're not here to flip your company. We're here to carry it forward."}
        items={[{"title":"Your Employees Stay","body":"We seek to maintain your team and continue building on the foundation you've established. Your people are part of the legacy."},{"title":"Direct, Transparent Process","body":"We work directly with you and your advisors — designed to maintain business health while setting it up for its next chapter."},{"title":"Operator, Not Investor","body":"Unlike PE firms, we have no portfolio competing for attention. When we acquire your business, it becomes our singular focus."}]}
      />
      <ContactSimple
        eyebrow={"Contact"}
        headline={"Let's start"}
        headlineAccent={"a conversation"}
        body={"Whether you're ready to sell today or simply exploring options, we'd love to hear from you. Reach out to Eric directly — every inquiry is kept strictly confidential."}
        email={"hello@mercerstreetcap.com"}
        phone={"(206) 486-5749"}
        location={"Seattle, Washington"}
      />
      </main>
      <FooterWordmark
        brandName={"Mercer Street Capital"}
        tagline={"Acquiring and operating exceptional businesses."}
        email={"hello@mercerstreetcap.com"}
        location={"Seattle, Washington"}
        copyright={"© 2025 Mercer Street Capital. All rights reserved."}
      />
    </>
  );
}
